id: PEEE0C13E
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: de
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    020afa394e434d2b9956a58e80db1368:
      title: Brief Dharmapālas Offering
      parent: General
    a0745b42b6584867bf642bf6958e9979:
      title: Brief Protectors Practice
      parent: General
    12d2acddf9e0477e9cdf6f26f6e4fb0e:
      title: Expeditious Activity Torma Offering
      parent: General
    d34b0a5bd6174f2194210e11d1367aca:
      title: Wayfaring Offering
      parent: General
    092ae94039d04d08af9e824fcbd9fae8:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    4c85c619a4e44418b2662180dfa2835c:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    8fe6f4aa6d66473fb21c503f5c95676c:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    0867e13e59ab4585a4d2304eab44f897:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    626c4145baaf4fc2b3e84adc5d1b786d:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    ec993ce090f04b7a90c1afe06fb61c1f:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    1ce11dc1913f4d16a79b7e904304ee4b:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    c6a9919ec09c4cef82a1fa81b95d3c4a:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    d62eb0083f5d40058a3f79244fa50e71:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    c32fca63c64a4481ab78fee2878da96e:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    caf6a179321c4aa4950bf764e79b86cf:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    b44931d0cfb24abda2ebcc7f0697e5ed:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    ecab0f19c49445c5975095fbe73e34d6:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    215031be737a4e5f9fc7141ed10f02c6:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    50539f5d43a747cc8f0dce59e63b0e89:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    a6c3258a937c4fca82b3a0fae94b7f76:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    ebb9aa30b4144fb38193e1637abd3922:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    cc63662c6c604e4cbab22fe5646126d7:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    d92286c9e1534b2ca112ccbfc3c0e31f:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    4245bd643ea949b58d8d0d767ad83c1e:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    34e30e046b974dee9f111865c7a761a7:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    0062d38fa1974d45b28527306ab06c5f:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.280727'
last_modified_at: '2022-03-01T03:27:20.280730'
